Require macOS 10.13+
Addresses

error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.13 or newer

which still occurs even with _LIBCPP_DISABLE_AVAILABILITY set.

Signed-off-by: Marcel Bargull <marcel.bargull@udo.edu>